# Generated by Django 2.2.16 on 2020-09-29 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_auto_20200926_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='nombre',
            field=models.CharField(choices=[('Co', 'Completo'), ('As', 'As'), ('Fa', 'Fajita'), ('Em', 'Empanada'), ('Ve', 'Vegetariano'), ('Sa', 'Sandwich'), ('Ju', 'Jugo natural'), ('Pa', 'Paila de huevo')], max_length=100),
        ),
    ]
