# Generated by Django 2.2.16 on 2020-09-29 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_auto_20200928_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='nombre',
            field=models.CharField(choices=[('Completo', 'Completo'), ('As', 'As'), ('Fajita', 'Fajita'), ('Empanada', 'Empanada'), ('Vegetariano', 'Vegetariano'), ('Sandwich', 'Sandwich'), ('Jugo natural', 'Jugo natural'), ('Paila de huevo', 'Paila de huevo')], max_length=100),
        ),
    ]
